* 3

** 3a

#+begin_quote
There are batteries nearby that can supply emergency power to the
escalator for just such an occasion. The batteries are each labeled
with their joltage rating, a value from 1 to 9. You make a note of
their joltage ratings (your puzzle input). For example:

987654321111111
811111111111119
234234234234278
818181911112111

The batteries are arranged into banks; each line of digits in your
input corresponds to a single bank of batteries. Within each bank, you
need to turn on exactly two batteries; the joltage that the bank
produces is equal to the number formed by the digits on the batteries
you've turned on. For example, if you have a bank like 12345 and you
turn on batteries 2 and 4, the bank would produce 24 jolts. (You
cannot rearrange batteries.)

You'll need to find the largest possible joltage each bank can
produce. In the above example:

In 987654321111111, you can make the largest joltage possible, 98, by
turning on the first two batteries.
In 811111111111119, you can make the largest joltage possible by
turning on the batteries labeled 8 and 9, producing 89 jolts.
In 234234234234278, you can make 78 by turning on the last two
batteries (marked 7 and 8).
In 818181911112111, the largest joltage you can produce is 92.
The total output joltage is the sum of the maximum joltage from each
bank, so in this example, the total output joltage is 98 + 89 + 78 +
92 = 357.

There are many batteries in front of you. Find the maximum joltage
possible from each bank; what is the total output joltage?
#+end_quote

*** Idea

A naive way to do this would be to search each line for "9.*9", then
"9.*8", then "9.*7", etc. This seems slow!

My approach would be to search for "9[0-9]", then "8[0-9]", then
"7[0-9]". This gives us the digit with the highest value, but avoids
the last character on the line.

Then search from just after the highest digit for "9", then "8", then
"7", etc.

This /should/ give the largest value, i.e. the /joltage/, for a line.

*** Code

Open the file and read line by line. Or read the data and split by
lines. We can process each line as we read it, or read them all into a
list and then process each item in the list. But either way, I think
the search is complex enough for its own function.

**** Imports

#+begin_src python :tangle 3a.py :comments both
import re
import sys
#+end_src

**** Search function

#+begin_src python :tangle 3a.py :comments both
def joltage(line):
    """
    Search line for the joltage, which is the highest value digit followed by
    the highest value digit after this first digit. Return the joltage.
    """

    # Search for first digit. If we find nothing, "decrement" the first
    # character. Continue searching until we find something. If for some reason
    # we don't find anything, yell about it, as it shouldn't happen.
    result = None
    for digit in range(9, -1, -1):
        pat1 = str(digit) + "[0-9]"
        result = re.search(pat1, line)
        if result:
            break
    if not result:
        # this shouldn't happen!
        sys.exit(f'No digits in "{line}"')
    first = digit

    # Now search for second digit, starting just after result from the search
    # above. Similar to above, start with "9" and "decrement" down to 0. And
    # again, if we don't find something, complain.
    result2 = None
    for digit in range(9, -1, -1):
        result2 = re.search(str(digit), line[result.start() + 1:])
        if result2:
            break
    if not result2:
        # This sholdn't happen!
        sys.exit(f'No second digit in "{line}"')
    second = digit

    return first * 10 + second
#+end_src

**** Create joltage sum

#+begin_src python :tangle 3a.py :comments both
joltage_sum = 0
#+end_src

**** Process input file

- Open file
- Read each line
  - compute joltage
  - add to joltage sum

#+begin_src python :tangle 3a.py :comments both
with open("input.txt", "r") as f:
    for line in f:
        joltage_sum += joltage(line)
#+end_src

**** Print joltage sum

#+begin_src python :tangle 3a.py :comments both
print(joltage_sum)
#+end_src
