* 6

** 6a

#+begin_example
As you try to find a way out, you are approached by a family of cephalopods! They're pretty sure they can get the door open, but it will take some time. While you wait, they're curious if you can help the youngest cephalopod with her math homework.

Cephalopod math doesn't look that different from normal math. The math worksheet (your puzzle input) consists of a list of problems; each problem has a group of numbers that need to be either added (+) or multiplied (*) together.

However, the problems are arranged a little strangely; they seem to be presented next to each other in a very long horizontal list. For example:

123 328  51 64 
 45 64  387 23 
  6 98  215 314
,*   +   *   +  

Each problem's numbers are arranged vertically; at the bottom of the problem is the symbol for the operation that needs to be performed. Problems are separated by a full column of only spaces. The left/right alignment of numbers within each problem can be ignored.

So, this worksheet contains four problems:

123 * 45 * 6 = 33210
328 + 64 + 98 = 490
51 * 387 * 215 = 4243455
64 + 23 + 314 = 401

To check their work, cephalopod students are given the grand total of adding together all of the answers to the individual problems. In this worksheet, the grand total is 33210 + 490 + 4243455 + 401 = 4277556.

Of course, the actual worksheet is much wider. You'll need to make sure to unroll it completely so that you can read the problems clearly.

Solve the problems on the math worksheet. What is the grand total found by adding together all of the answers to the individual problems?
#+end_example

*** Ideas

We read files by rows, but these problems are arranged in columns.
This is a file of 5 rows, 1000 columns per row, meaning 1000 problems.
Create a list of 1000 lists to hold the problems. As we read the 5 rows,
append the fields of those rows to the list for each problem. Convert
the strings to integers for the rows of numbers.

At this point, the problems should look something like

#+begin_src python
[58, 6724, 1311, 6245, '+']
#+end_src

So in this case we want to add the 4 numbers together. We can use

- functools.reduce() to apply a function to the first 4 items until we
  reduce it to a single value
- operator.add() as the function to apply

Like so:

#+begin_src python
import functools
import operator

answer = functools.reduce(operator.add, problems[0][:-1])
#+end_src

Alternatively, we could use

#+begin_src python
sum(problems[0][:-1])
#+end_src

But this makes two sets of code to do sums or products. If we use
functools.reduce, we can also set a variable fn to either operator.add
or operator.mul and use it when we call reduce.

Similarly, if the last item is '*', use operator.mul.

Just add up all the answers as we go, or use sum()

*** Code

**** Imports

#+begin_src python :tangle 6.py :comments both
import functools
import operator
import re
import sys
#+end_src

**** Create problems list

#+begin_src python :tangle 6.py :comments both
problems = []
for i in range(1000):
    problems.append([])
#+end_src


**** Read file into problems

#+begin_src python :tangle 6.py :comments both
with open("input.txt", "r") as f:
    for line in f:
        # There are 1 or more spaces between fields. Make it a single space
        # throughout. Also strip any trailing spaces
        line = re.sub(" +", " ", line.rstrip())
        fields = line.split()
        for i in range(1000):
            if fields[i].isdecimal():
                problems[i].append(int(fields[i]))
            else:
                problems[i].append(fields[i])
#+end_src


**** Sum up answers

#+begin_src python :tangle 6.py :comments both
answers_sum = 0

for p in problems:
    if p[-1] == '+':
        fn = operator.add
    elif p[-1] == '*':
        fn = operator.mul
    else:
        sys.exit(f'Unknown operator "{p[-1]}"')

    answers_sum += functools.reduce(fn, p[:-1])

print(answers_sum)
#+end_src

** 6b

#+begin_example
ephalopod math is written right-to-left in columns. Each number is given in its own column, with the most significant digit at the top and the least significant digit at the bottom. (Problems are still separated with a column consisting only of spaces, and the symbol at the bottom of the problem is still the operator to use.)

Here's the example worksheet again:

123 328  51 64 
 45 64  387 23 
  6 98  215 314
,*   +   *   +  
Reading the problems right-to-left one column at a time, the problems are now quite different:

The rightmost problem is 4 + 431 + 623 = 1058
The second problem from the right is 175 * 581 * 32 = 3253600
The third problem from the right is 8 + 248 + 369 = 625
Finally, the leftmost problem is 356 * 24 * 1 = 8544
Now, the grand total is 1058 + 3253600 + 625 + 8544 = 3263827.

Solve the problems on the math worksheet again. What is the grand total found by adding together all of the answers to the individual problems?
#+end_example

*** Ideas

I wish the Python "re" package had a way to specify matching
right-to-left. This would probably be a bit easier then, if I could
get my head around it!

In reading the Python regular expression syntax, I came across
"(?=...)":

#+begin_quote
Matches if ... matches next, but doesn’t consume any of the string.
This is called a lookahead assertion. For example, Isaac (?=Asimov)
will match 'Isaac ' only if it’s followed by 'Asimov'.
#+end_quote

I'm now looking for regular expressions that start with 1 or more
digits, then 0 or more spaces, then a non-matching space:

#+begin_example
\d+ *(?= )
#+end_example

I don't want to consume the trailing space as part of the match, as
I'd just want to trim it off again.

Using Pythons re.findall() is nice in that it can find all of the
matches and return a list. Nice.

So first, read the data and split it into lines. Then for each line
split using re.findall(). Then walk through i in range(1000) appending
to problems[i]. Then finally, parse into numbers starting with the
rightmost column or each item, using string addition to create a
numeric string, ignoring spaces. Finally, convert to an int.

Hmm, maybe leave the parsed fields in a list of lists. Then do this
string addition dance and finally put the numbers into problems[i].

Trying this out manually, I found that I got 1000 tokens for the first
3 lines, but only 999 tokens on the 4th line! Looking a bit closer, it
looks like the last token on line 4 is "3595" but doesn't have a space
at the end. Instead, it has end-of-line. So, should I modify the
regular expression to match this?

Also, given the examples on the web page, I wonder if I'm doing this
wrong. It seems like short strings could also have leading spaces
rather than trailing.

I wonder if the operator is always in the left-most character of its
field? If so, it might be helpful to parse that first to get an idea
of field size.

I should also check the field sizes for consistency.
